"""Structure-first layout analysis for historical Chinese documents."""

from .layout import (
    Box,
    LayoutConfig,
    LayoutDocument,
    LayoutNode,
    RegionCell,
    RegionGraph,
    RuleGraph,
    RuleSegment,
    detect_layout,
    detect_region_graph,
    detect_rule_graph,
    draw_layout,
    draw_region_graph,
    draw_rule_graph,
)
from .content_graph import (
    ContentEdge,
    ContentGraph,
    LaneObservation,
    StreamGroup,
    TextStream,
    detect_content_graph,
    draw_content_graph,
)
from .glyph_graph import (
    GlyphChain,
    GlyphGraph,
    GlyphNode,
    GlyphRecord,
    GlyphRelation,
    detect_glyph_graph,
    draw_glyph_graph,
    draw_record_graph,
)

__all__ = [
    "Box",
    "ContentEdge",
    "ContentGraph",
    "GlyphChain",
    "GlyphGraph",
    "GlyphNode",
    "GlyphRecord",
    "GlyphRelation",
    "LayoutConfig",
    "LayoutDocument",
    "LayoutNode",
    "LaneObservation",
    "StreamGroup",
    "RegionCell",
    "RegionGraph",
    "RuleGraph",
    "RuleSegment",
    "TextStream",
    "detect_content_graph",
    "detect_glyph_graph",
    "draw_content_graph",
    "draw_glyph_graph",
    "draw_record_graph",
    "detect_layout",
    "detect_region_graph",
    "detect_rule_graph",
    "draw_layout",
    "draw_region_graph",
    "draw_rule_graph",
]
__version__ = "1.5.0.dev0"
